Provide support for reveal.js version 3.4.1
The Docker image has been updated to accommodate version 3.4.1 of
reveal.js. The Dockerfiles have been re-written to try and
optimise image size and layer count.

The Tini init process has been upgraded to version 0.14.0.

The onbuild entrypoint script provides a new config flag,
--syntaxStyle, which allows an alternative highlight.js style to
be specified. It assumes a corresponding CSS file is available
in lib/css.

An Alpine Linux image has been added for those wary of image size.

diff --git a/onbuild/Dockerfile b/onbuild/Dockerfile
--- a/onbuild/Dockerfile
+++ b/onbuild/Dockerfile
@@ -1,61 +1,65 @@
 FROM node:4-slim
 
-MAINTAINER Nigel Brown <nigel@windsock.io>
+# Define build time arguments
+ARG BUILD_DATE
+ARG VCS_REF
 
 # npm loglevel in base image is verbose, adjust to warnings only
 ENV NPM_CONFIG_LOGLEVEL warn
 
-# Add utilities for installation of dependencies
-RUN apt-get update && \
-    apt-get install -y --no-install-recommends \
-        g++ \
-        make \
-        python \
-        wget && \
-    rm -rf /var/lib/apt/lists/*
-
-# Add tini as PID 1 to facilitate correct signal handling
-# See https://github.com/nodejs/node-v0.x-archive/issues/9131
-ENV TINI_VERSION=v0.10.0 \
+# Set environment variables for tini GitHub repo
+ENV TINI_VERSION=v0.14.0 \
     TINI_REPO=https://github.com/krallin/tini
-RUN gpg --keyserver ha.pool.sks-keyservers.net --recv-keys 6380DC428747F6C393FEACA59A84159D7001A4E5 && \
-    wget -qO /bin/tini $TINI_REPO/releases/download/$TINI_VERSION/tini && \
-    wget -qO /bin/tini.asc $TINI_REPO/releases/download/$TINI_VERSION/tini.asc && \
-    gpg --verify /bin/tini.asc && \
-    rm /bin/tini.asc && \
-    chmod +x /bin/tini
 
-# Retrieve reveal.js from Github repsoitory
-ENV VERSION=3.3.0 \
+# Set environment variables for reveal.js GitHub repo
+ENV VERSION=3.4.1 \
     REPO=https://github.com/hakimel/reveal.js \
-    SHA=45dc8caeb1a1a81d74293552ea3a408bc463dc3e
-RUN wget -qO /tmp/reveal.js.tar.gz $REPO/archive/$VERSION.tar.gz && \
-    echo "$SHA /tmp/reveal.js.tar.gz" | sha1sum --check - && \
-    tar -xzf /tmp/reveal.js.tar.gz -C / && \
-    rm -f /tmp/reveal.js.tar.gz && \
-    mv reveal.js-$VERSION reveal.js
+    SHA1=64bf63c54e2a01ebcec905233527872940317426
 
-# Set working directory for container
-WORKDIR /reveal.js
-
-# Create user, install grunt CLI and dependencies, and set ownership
-RUN useradd -r revealjs && \
-    npm install -g grunt-cli && \
-    npm install && \
-    npm cache clean && \
-    rm -rf /tmp/npm* && \
-    chown -R revealjs:revealjs /reveal.js
-
-# Set user
-USER revealjs
-
-# Expose default port
-EXPOSE 8000
+RUN set -ex \
+    \
+    && apt-get update \
+    \
+# Install necessary utilities
+    && apt-get install -y --no-install-recommends bzip2 \
+#    \
+# Add tini for handling signals
+# https://github.com/nodejs/docker-node/blob/master/docs/BestPractices.md#handling-kernel-signals
+    && gpg --keyserver ha.pool.sks-keyservers.net --recv-keys 6380DC428747F6C393FEACA59A84159D7001A4E5 \
+    && wget -qO /bin/tini $TINI_REPO/releases/download/$TINI_VERSION/tini \
+    && wget -qO /bin/tini.asc $TINI_REPO/releases/download/$TINI_VERSION/tini.asc \
+    && gpg --verify /bin/tini.asc \
+    && rm /bin/tini.asc \
+    && chmod +x /bin/tini \
+    \
+# Fetch reveal.js
+    && wget -qO /tmp/reveal.js.tar.gz $REPO/archive/$VERSION.tar.gz \
+    && echo "$SHA1 /tmp/reveal.js.tar.gz" | sha1sum --check - \
+    && tar -xzf /tmp/reveal.js.tar.gz -C / \
+    && rm -f /tmp/reveal.js.tar.gz \
+    && mv reveal.js-$VERSION reveal.js \
+    \
+# Install dependencies
+    && mkdir -p /reveal.js/node_modules \
+    && npm install -g grunt-cli \
+    && npm install --prefix /reveal.js \
+    \
+# Clean up
+    && npm cache clean \
+    && rm -rf /tmp/npm* /tmp/phantomjs \
+    && apt-get purge -y bzip2 \
+    && rm -rf /var/lib/apt/lists/* \
+    && chown -R node:node /reveal.js
 
 # Add script for processing runtime configuration options
 COPY docker-entrypoint.sh /entrypoint.sh
 
-# Add container entrypoint
+WORKDIR /reveal.js
+
+USER node
+
+EXPOSE 8000
+
 ENTRYPOINT ["/bin/tini", "--", "/entrypoint.sh"]
 
 # Add presentation data (index.html, slides.md, media/*)
@@ -69,13 +73,13 @@ ONBUILD COPY js/ ./js/
 ONBUILD COPY plugin/ ./plugin/
 ONBUILD COPY lib/ ./lib/
 
-# Provide image labels in support of the Label Schema (http://label-schema.org)
-ARG BUILD_DATE
-ARG VCS_REF
+# Define image metadata (https://microbadger.com/labels)
 LABEL org.label-schema.build-date=$BUILD_DATE \
-      org.label-schema.license="MIT" \
-      org.label-schema.version="3.3.0" \
-      org.label-schema.url="https://github.com/hakimel/reveal.js" \
+      org.label-schema.docker.dockerfile="/onbuild/Dockerfile" \
+      org.label-schema.license=MIT \
+      org.label-schema.name="reveal.js" \
+      org.label-schema.version=$VERSION \
+      org.label-schema.url=https://github.com/hakimel/reveal.js \
       org.label-schema.vcs-ref=$VCS_REF \
       org.label-schema.vcs-url="https://github.com/nbrownuk/docker-revealjs.git" \
-      org.label-schema.vcs-type="Git"
+      org.label-schema.vcs-type=Git
